version: "3.8"
services:
  mysql:
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  batch:
    depends_on:
      - mysql
      - zipkin
      - rabbit
    build:
      dockerfile: dockerfile
    image: batch-cnab
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_PASS: secret
      DB_USER: root
      ZIPKIN_HOST: localhost
      ZIPKIN_HTTP: http
      ZIPKIN_PORT: 9411