version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: root@123
      ACCEPT_EULA: Y
    deploy:
      resources:
        limits:
          cpus: "0.5"
  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
    deploy:
      resources:
        limits:
          cpus: "0.5"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    deploy:
      resources:
        limits:
          cpus: "0.5"
  batch:
    depends_on:
      - sqlserver
      - rabbit
      - zipkin
    build:
      dockerfile: dockerfile
    image: batch-cnab
    restart: always
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
    environment:
      DB_PASS: secret
      DB_USER: root
      ZIPKIN_HOST: localhost
      ZIPKIN_HTTP: http
      ZIPKIN_PORT: 9411