logging:
  level:
    'org.hibernate.SQL': info
    'org.hibernate.stat': debug
    'com.h2database:h2': info
    'com.batsworks.batch.config.utils': debug
    'com.batsworks.batch': debug

server:
  compression:
    enabled: true
    mime-types: application/json, application/xml,text/html,image/jpeg

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_HTTP:http}://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

spring:
  application.name: CNAB_BATCH
  main:
    allow-bean-definition-overriding: true
    banner-mode: OFF
  batch:
    jdbc.initialize-schema: ALWAYS
    job.enabled: false
  datasource:
    hikari.connection-timeout: 5000
    #    url: jdbc:sqlserver://;serverName=localhost;databaseName=CNAB_CODES;trustServerCertificate=true;
    #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    username: SA
    #    password: Felipe@2001
    url: jdbc:mysql://localhost:3306/CNAB_CODES?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    #    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
      jdbc.batch_size: 30
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    properties:
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: false
        generate_statistics: false
        order_inserts: true
        order_updates: true
        javax.cache.provider: "org.ehcache.jsr107.EhcacheCachingProvider"
        session:
          events.log.LOG_QUERIES_SLOWER_THAN_MS: 150
          region.factory_class: jcache
  sql.init.mode: ALWAYS
  h2.console.enabled: true
  rabbitmq:
    host: localhost
    port: 5674
    username: guest
    password: guest

configuration:
  max_size: 3000
  default_folder: tmp
  code_prefix: _

documentation:
  title: ${spring.application.name}
  version: 1.0.1
  url: https://www.linkedin.com/in/felipebatista-silva/
  description: "projeto para para de batch cnab"
  name: "Felipe Batista da Silva"
  email: "felipeb2silva@gmail.com"