logging:
  level:
    sql: info
    'org.hibernate.SQL': info
    'com.h2database:h2': info
    'com.batsworks.batch.config.utils': debug

spring:
  main:
    banner-mode: OFF
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/CNAB_CODES?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        order_inserts: true
        order_pdates: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true



configuration:
  max_size: 3000