spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:file:./data/db
    driver-class-name: org.h2.Driver
    username: bats
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true