logging:
  level:
    sql: info
    'org.hibernate.SQL': info
    'com.h2database:h2': info
    'com.batsworks.batch.config.utils': debug

spring:
  main:
    banner-mode: OFF
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:sqlserver://;serverName=localhost;databaseName=CNAB_CODES;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: SA
    password: Felipe@2001
#    url: jdbc:mysql://localhost:3306/CNAB_CODES?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password:
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        order_inserts: true
        order_pdates: true
  sql:
    init:
      mode: NEVER
  h2:
    console:
      enabled: true



configuration:
  max_size: 3000