logging:
  level:
    sql: info
    'org.hibernate.SQL': info
    'com.h2database:h2': info
    'com.batsworks.batch.config.utils': debug

spring:
  main:
    banner-mode: OFF
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:h2:file:./data/db
    driver-class-name: org.h2.Driver
    username: bats
    password:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true