package com.batsworks.batch.domain.records;

import java.math.BigDecimal;

public record Cnab400(
        String identRegistro,
        String agenciaDebito,
        String digitoAgencia,
        String razaoAgencia,
        String contaCorrente,
        String digitoConta,
        String identBeneficiario,
        String controleParticipante,
        String codigoBanco,
        Integer campoMulta,
        BigDecimal percentualMulta,
        Long nossoNumero,
        String digitoConferenciaNumeroBanco,
        Long descontoDia,
        Long condicaoEmpissaoPapeladaCobranca,
        String boletoDebitoAutomatico,
        Long identificacaoOcorrencia,
        String numeroDocumento,
        String dataVencimento,
        BigDecimal valorTitulo,
        Long especieTitulo,
        String dataEmissao,
        String primeiraInstrucao,
        String segundaInstrucao,
        BigDecimal moraDia,
        String dataLimiteDescontoConcessao,
        BigDecimal valorDesconto,
        BigDecimal valorIOF,
        String valorAbatimento,
        Long tipoPagador,
        String nomePagador,
        String endereco,
        String primeiraMensagem,
        String cep,
        String sufixoCEP,
        String segundaMensagem,
        String sequencialRegistro,
        String line
) {

   public Cnab400 withLine(int line) {
        return new Cnab400(
                this.identRegistro,
                this.agenciaDebito,
                this.digitoAgencia,
                this.razaoAgencia,
                this.contaCorrente,
                this.digitoConta,
                this.identBeneficiario,
                this.controleParticipante,
                this.codigoBanco,
                this.campoMulta,
                this.percentualMulta,
                this.nossoNumero,
                this.digitoConferenciaNumeroBanco,
                this.descontoDia,
                this.condicaoEmpissaoPapeladaCobranca,
                this.boletoDebitoAutomatico,
                this.identificacaoOcorrencia,
                this.numeroDocumento,
                this.dataVencimento,
                this.valorTitulo,
                this.especieTitulo,
                this.dataEmissao,
                this.primeiraInstrucao,
                this.segundaInstrucao,
                this.moraDia,
                this.dataLimiteDescontoConcessao,
                this.valorDesconto,
                this.valorIOF,
                this.valorAbatimento,
                this.tipoPagador,
                this.nomePagador,
                this.endereco,
                this.primeiraMensagem,
                this.cep,
                this.sufixoCEP,
                this.segundaMensagem,
                this.sequencialRegistro,
                String.valueOf(line)
        );
    }

}