package com.batsworks.batch.domain.records;

public record CnabWritter(
       String campo1,
       String campo2,
       String campo3,
       String campo4,
       String campo5,
       String campo6,
       String campo7,
       String campo8,
       String campo9,
       String campo10,
       String campo11,
       String campo12,
       String campo13,
       String campo14,
       String campo15,
       String campo16,
       String campo17,
       String campo18,
       String campo19,
       String campo20,
       String campo21,
       String campo22,
       String campo23,
       String campo24,
       String campo25,
       String campo26,
       String campo27,
       String campo28,
       String campo29,
       String campo30,
       String campo31,
       String campo32,
       String campo33,
       String campo34,
       String campo35,
       String campo36,
       String campo37,
       String campo38,
       String campo39,
       String campo40) {
}
