package com.batsworks.batch.config.exception;

import lombok.Getter;

@Getter
public enum StatusEnum {

    UNKNOW_ERROR("UNKNOW_ERROR"),
    ERROR_WITH_MESSAGE("ERROR_WITH_MESSAGE"),
    ERROR_WITHOUT_MESSAGE("ERROR_WITHOUT_MESSAGE"),
    ARQUVIVO_SUCESS("ARQUVIVO_SUCESS"),
    ARQUVIVO_PROCESSANDO("ARQUVIVO_PROCESSANDO"),
    ARQUVIVO_PROCESSADO_ERRO("ARQUVIVO_PROCESSADO_ERRO"),
    ARQUVIVO_PROCESSADO_SUCESSO("ARQUVIVO_PROCESSADO_SUCESSO"),
    ARQUVIVO_DOWNLOADING("ARQUVIVO_DOWNLOADING"),
    ARQUVIVO_DOWNLOAD_ERROR("ARQUVIVO_DOWNLOAD_ERROR");

    private final String error;

    StatusEnum(String error){
        this.error = error;
    }

}
